apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: jenkins
  name: frontend-admin-ingress
  labels:
    env: production
    tier: frontend
    app: admin
    name: frontend-admin-ingress
spec:
  rules:
    - host: admin.192.168.100.66.nip.io # TODO
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend-admin
              servicePort: 3000